### ISSUE TITLE
saas_client javascript

### ISSUE THREAD

**Issue by kaerdsar** [yelizariev/odoo-saas-tools#10]
I pushed a commit with a variant to show well the message in a fresh database. There is a little problem, the javascript functions can't be inherited because the addon saas_client is server_wide and loads first than the addon mail. We can call the mail javascript function first but later will be executed again. Tell me if you want we look for a more elegant solution to this issue.

**Comment by kaerdsar** [comment]
The other thing I can do is separate the saas_client addon in two differents. In other case try to fix the odoo framework bug. Tell me your idea.

**Comment by yelizariev** [comment]
Closed, because we remove saas_client from server wide: https://github.com/yelizariev/odoo-saas-tools/pull/6#issuecomment-130573620
