### ISSUE TITLE
saas_portal: certificate verify failed

### ISSUE THREAD

**Issue by tarzan0820** [yelizariev/odoo-saas-tools#12]
Hello @yelizariev,  instances of requests.get(url) fail when using a self-signed SSL or in my case one from Godaddy.

Do you think it is a good idea to stop requests.get from verifying certificates by setting verify=False?

What are your thoughts on this

**Comment by yelizariev** [comment]
not verified https is better than http, but worse than verified https.

With regards to source, it's better to add verify_ssl field to saas_portal.server, than hardcode verify=False

**Comment by tarzan0820** [comment]
I totally agree with you; are you going to do this or should i attempt and send you a pull request

**Comment by yelizariev** [comment]
You could make pull request yourself. This issue is a low priority for us.

**Comment by shingonoide** [comment]
:+1:
