### ISSUE TITLE
issue in step 6: Create plan

### ISSUE THREAD

**Issue by jack-solutions** [yelizariev/odoo-saas-tools#14]
I've done configuration upto step 5. but in step 6 whenever i try to Create template DB then new window will open and it gives 404 not found error.
odoo log:
2015-08-24 07:54:43,938 30006 INFO odoo.local werkzeug: 127.0.0.1 - - [24/Aug/2015 07:54:43] "GET /oauth2/auth?scope=userinfo+force_login+trial+skiptheuse&state=%7B%22lang%22%3A+%22en_US%22%2C+%22tz%22%3A+%22Asia%2FCalcutta%22%2C+%22d%22%3A+%22t1.odoo.local%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&redirect_uri=http%3A%2F%2Fs1.odoo.local%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=1b62941e-4a35-11e5-b08b-00e04c049539 HTTP/1.1" 302 -
2015-08-24 07:54:43,954 30006 INFO None werkzeug: 127.0.0.1 - - [24/Aug/2015 07:54:43] "GET /saas_server/new_database HTTP/1.1" 404 -

**Comment by yelizariev** [comment]
Are you sure, that you set Database Name for saas server?
Which link (with domain) do you see in your browser, when get 404 error.

I close the issue. If it happens, that you configure system properly, I would reopen it.

**Comment by jack-solutions** [comment]
"Are you sure, that you set Database Name for saas server?"
-what kind of database name? and where will i set?
-when i click on create template db in Plans(step 6) then it will give 404 error.

following are the screenshots of my configuration. 
server database (s1.odoo.local):
![providers - odoo 2015-08-24 15-16-20](https://cloud.githubusercontent.com/assets/5101493/9437402/beb42ef0-4a73-11e5-9eb9-19af0d4140d6.png)

Portal setting:
![saas portal settings - odoo 2015-08-24 15-18-43](https://cloud.githubusercontent.com/assets/5101493/9437454/0cd4ee12-4a74-11e5-9697-536ef0e5225f.png)

Registering Server Database in Main Database:
![servers - odoo 2015-08-24 15-20-02](https://cloud.githubusercontent.com/assets/5101493/9437478/392f56be-4a74-11e5-9037-86f6849967ad.png)

Create plan:
![plans - odoo 2015-08-24 15-21-25](https://cloud.githubusercontent.com/assets/5101493/9437523/7bfa6aa6-4a74-11e5-8866-0f35ff8aac07.png)

**Comment by yelizariev** [comment]
Do you have dbfilter=%h in configuration file?

**Comment by jack-solutions** [comment]
yes 
i've did that changed in odoo/openerp/tools/config.py

group.add_option("--db-filter", dest="dbfilter", my_default='%h',help="Filter listed database", metavar="REGEXP")

originally it was my_default='.*'

**Comment by yelizariev** [comment]
Try to run with --db-filter=%h instead

**Comment by jack-solutions** [comment]
already tried but got this:
2015-08-24 10:26:00,442 7286 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 1413, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by yelizariev** [comment]
show me screenshot of 404 error in browser with url address

**Comment by yelizariev** [comment]
Also, be sure, that you do this from step 5

click [Open Server]. Be sure that you allow pop-ups in your browser.
log out from SaaS Server
click "Log in via SaaS Portal"

**Comment by jack-solutions** [comment]
in step 5: i allow pop-ups in my browser.
and then new window will ask the login details. now here are you asking me to click Login in via saas portal instead of login button. because if i click that then it will also give 404 error. with this url:  http://odoo.local/oauth2/auth?state=%7B%22p%22%3A+4%2C+%22r%22%3A+%22http%253A%252F%252Fs1.odoo.local%252Fweb%253F%22%2C+%22d%22%3A+%22s1.odoo.local%22%7D&redirect_uri=http%3A%2F%2Fs1.odoo.local%2Fauth_oauth%2Fsignin&response_type=token&client_id=6d2d5538-4a29-11e5-9d3a-00e04c049539&debug=False&scope=userinfo

and in plan i got this in url:
http://s1.odoo.local/saas_server/new_database?access_token=h6SMYt8qmXTa5UdaX99hbBm5kREHhs&token_type=Bearer&state=%7B%22lang%22%3A+%22en_US%22%2C+%22tz%22%3A+%22Asia%2FCalcutta%22%2C+%22d%22%3A+%22t1.odoo.local%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&expires_in=3600&scope=userinfo+force_login+trial+skiptheuse

Crate template db:
![screenshot from 2015-08-24 16 17 58](https://cloud.githubusercontent.com/assets/5101493/9438450/738e55b0-4a7b-11e5-9bb8-c3e024629361.png)

**Comment by yelizariev** [comment]
You have to use
./odoo.py --db-filter=%h 
and database name (i.e. one that you specify at /web/database/manager) for server should be
s1.odoo.local

**Comment by jack-solutions** [comment]
In step 5 as you have mention to do following steps:
click [Open Server]. Be sure that you allow pop-ups in your browser.
log out from SaaS Server
click "Log in via SaaS Portal"
now yesterday when i am trying to login via saas portal it gives 404 error. 
but now it gives access denied error.
![login localhost 2015-08-25 09-53-45](https://cloud.githubusercontent.com/assets/5101493/9458698/32ed4c0c-4b0f-11e5-80e0-3a894ab387ce.png)

also i want to know that where should i install saas_client module. i think it should be installed in s1.odoo.local(server database).

**Comment by yelizariev** [comment]
saas_client is installed automatically.

**Comment by yelizariev** [comment]
Have you installed saas_portal module on s1.odoo.local?

**Comment by yelizariev** [comment]
ok, I guess you do

**Comment by yelizariev** [comment]
Which version do you use?
Check OAuth tab in Administration user form in s1.odoo.local
You have to have OAuth User ID = 1 and 
OAuth Provider = SaaS 

Do you use everywhere Administration login?

**Comment by jack-solutions** [comment]
in which module you have given saas_client dependency. because in my case it was not installed automatically. and also why i am getting Access denied error while login via saas portal.

**Comment by yelizariev** [comment]
saas_client will be installed when you create Client Database

**Comment by jack-solutions** [comment]
Have you installed saas_portal module on s1.odoo.local?
-That means i have to install saas_server and saas_portal modules in s1.odoo.local and saas_portal and saas_portal_\* modules in odoo.local database.

saas_client will be installed when you create Client Database
-How can i create client database. 
i have tried by clicking create button in s1,odoo.local database under Saas Server / SaaS/ database.
but those fields have access issue(for admin user).
![databases - odoo 2015-08-25 10-41-09](https://cloud.githubusercontent.com/assets/5101493/9459160/d3d5bef0-4b15-11e5-87bb-e5c82d7de2bd.png)

Check OAuth tab in Administration user form in s1.odoo.local
You have to have OAuth User ID = 1 and
OAuth Provider = SaaS 
see the following screenshot.
![users - odoo 2015-08-25 10-45-20](https://cloud.githubusercontent.com/assets/5101493/9459168/181ace02-4b16-11e5-9ad3-0892979ea0e4.png)

**Comment by yelizariev** [comment]
Sorry, it was typo. It should be

Have you installed saas_**server** module on s1.odoo.local?

**Comment by jack-solutions** [comment]
yes

**Comment by yelizariev** [comment]
> How can i create client database. 

You have to create database template first

**Comment by jack-solutions** [comment]
from where? saas server (s1.odoo.local)

**Comment by yelizariev** [comment]
We've updated saas_portal, so now there is no extra steps below in step 5.

Update saas_portal and create new Plan

**Comment by yelizariev** [comment]
> from where? saas server (s1.odoo.local)

via "Create client" button on Plan's form

**Comment by yelizariev** [comment]
little mistake:

Update saas_portal and create new **Server**

**Comment by jack-solutions** [comment]
-still login via saas portal gives Access Denied.

-don't know why but saas_client is still not installed. my question is where can i install it manually. (either in saas server or saas portal, i guess it should be installed in saas server(s1.odoo.local))

-after saving plan when i click on create client gives this error:

![screenshot from 2015-08-25 14 03 00](https://cloud.githubusercontent.com/assets/5101493/9462258/2a342cde-4b32-11e5-9ec8-92fb14426815.png)

Traceback (most recent call last):
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/mrugank/odoo-dev/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo-saas/saas_portal/models/wizard.py", line 114, in apply
    url = wizard.plan_id._create_new_database(dbname=wizard.name, partner_id=wizard.partner_id.id)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/home/mrugank/odoo-dev/odoo-saas/saas_portal/models/saas_portal.py", line 200, in _create_new_database
    server.action_sync_server()
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mrugank/odoo-dev/odoo/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/home/mrugank/odoo-dev/odoo-saas/saas_portal/models/saas_portal.py", line 117, in action_sync_server
    data = simplejson.loads(res.text)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yelizariev** [comment]
> -after saving plan when i click on create client gives this error:

you have to create template first.

It's issue, that Create Client is visible for Plan without template. We will fix it (cc @kaerdsar )

**Comment by yelizariev** [comment]
> -still login via saas portal gives Access Denied.

You don't need to login via saas if you updated saas_portal

You should click "Create Template".

**Comment by jack-solutions** [comment]
-You should click "Create Template".
after updating saas_portal i have followed updated step 5.
but if i click on create template db it gives :

![screenshot from 2015-08-25 15 09 32](https://cloud.githubusercontent.com/assets/5101493/9463567/0b75571a-4b3b-11e5-92ac-f23150de1d04.png)

with this url : http://s1.odoo.local/saas_server/new_database#access_token=juX1YvAY2NuyEcHHDQV3q9SPqbL4TE&token_type=Bearer&state=%7B%22lang%22%3A+%22en_US%22%2C+%22tz%22%3A+%22Asia%2FCalcutta%22%2C+%22d%22%3A+%22t1.odoo.local%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&expires_in=3600&scope=userinfo+force_login+trial+skiptheuse

-whatever i've tried yet(for create template) it gives 404 error.
-please also help: where can i install saas_client module.

Thank you for your help.

**Comment by yelizariev** [comment]
> -please also help: where can i install saas_client module.

saas_client is useless, if you have issue with s1.odoo.local

**Comment by yelizariev** [comment]
@jack-solutions contact me on hangouts: https://plus.google.com/+IvanYelizariev/

**Comment by yelizariev** [comment]
So, the issue was in apache configuration.

**Comment by jack-solutions** [comment]
yes, I've changed the apache config  so that it will pass host header and it works. :+1:  
Thank you so much.

**Comment by yelizariev** [comment]
Great, thank you for reporting. I've clarified description file according to your experience.

**Comment by kaerdsar** [comment]
I'm going to fix this bug.

Other issue:
What do you think about saas_route53?. I saw a pull request.

César

**Comment by infoelliex** [comment]
Hi Jack and Ivan,

I also have the same issue. How do you change the apache config to pass the host header to make it work? 

I try modify the site-available/000-default.conf by adding 

<VirtualHost *:*>
    ProxyPreserveHost On

```
# Servers to proxy the connection, or;
# List of application servers:
# Usage:
# ProxyPass / http://[IP Addr.]:[port]/
# ProxyPassReverse / http://[IP Addr.]:[port]/
# Example: 
ProxyPass / http://0.0.0.0:8069/
ProxyPassReverse / http://0.0.0.0:8069/

ServerName localhost
```

</VirtualHost>

I replace the 0.0.0.0 with ip address, adding different port, or add /saas_server etc and none of them work. I still getting the 404 not found. Please help. Thank you very much. 

  File "/odoo/custom/addons/saas_portal/models/saas_portal.py", line 292, in create_template
    raise Warning(msg)
Warning: Status Code - 404
Reason - NOT FOUND

**Comment by infoelliex** [comment]
The 404 not found issue was due to my incorrect configuration on the /etc/hosts and nginx settings. Because of Ivan's advice, the 404 not found issue was resolved. Thank you very much.

**Comment by nhkhoaus** [comment]
hi Yelizariev 
i install saas server and  client, it ok, 
i create :
     database name : axx   correspond  domain name : axx.company.com
     database name : bxx   correspond  domain name : bxx.company.com
     ........
when I enter website, outside the username and password, and then select database: axx, bxx ..
how to config for system auto select database correct, for example
axx.company.com  ->  axx
bxx.company.com  ->  bxx
...
user not select database
I use nginx

many thanks.

**Comment by soaprofessional** [comment]
Hi @yelizariev / @jack-solutions ,

I am facing the same issue of 404 error when clicking on the create template step.
Can you please share the fix for this? My host file looks like below and I have attached the nginx-config file
[nginx.conf.docx](https://github.com/it-projects-llc/odoo-saas-tools/files/853215/nginx.conf.docx)

127.0.0.1 s1.odoo.local # portal
127.0.0.1 odoo.local # server
127.0.0.1 t1.odoo.local # template
127.0.0.1 client-1.odoo.local #client
127.0.0.1       localhost

**Comment by 360org** [comment]
You lost domain template when trying to add template.
you have to config every template you want on the host before generate them.
like: 127.0.0.1 your-template-name.com

**Comment by soaprofessional** [comment]
@W360S ,

I am following the manual installation instruction as per https://github.com/it-projects-llc/odoo-saas-tools/blob/10.0/docs/install.rst
I did add the template in the host file (127.0.0.1 client-1.odoo.local) and followed the instructions till step 5 as per the above installation guide . While creating the template DB (clicking "Create Template DB" button) , I am getting 404 error jst like what @jack-solutions was getting.  Any help to fix this will be highly appreciated.

**Comment by 360org** [comment]
ad my skype at: live:chaulb i may help.

**Comment by soaprofessional** [comment]
Nevermind, I fixed the 404 issue. The problem was with the db filter in /etc/odoo/odoo.conf file .
I had below configuration in odoo.conf:
; dbfilter = .*
 dbfilter = ^%h$

I deleted the first dbfilter line (; dbfilter = .*) and the space in the beginning of second line  and the 404 error was gone.

**Comment by 360org** [comment]
nice

**Comment by yelizariev** [comment]
I made a blog post about dbfilter issue https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found

**Comment by Crux-un** [comment]
does the odoo saas tools run on enterprise version of 10

**Comment by 360org** [comment]
ofcause no @Crux-un

**Comment by Crux-un** [comment]
@W360S Is there a tutorial how to install saas with community, i get lots of errors and modules not found.. i downloaded the version on GitHub

**Comment by 360org** [comment]
@Crux-un you need to check carefully, learn one by one, step by step, saas is a good system but you cant be expert when the first time you meet :) same me from beginning.at the end if you can't setup ping me I can help.
