### ISSUE TITLE
SaaS Base

### ISSUE THREAD

**Issue by kaerdsar** [yelizariev/odoo-saas-tools#7]
I'm working on a saas_base addon to collect base models in saas solution.

Maybe we need also a saas_server.database model because a template database is not a client, it's just a database. Anyway it has a client_id field like saas_portal.database. The difference is we don't have an oauth.application on a server.

We have 3 concepts:
- Client for authentication
- Physical database
- Client in SaaS

Maybe we can join oauth.application and saas_x.database in a single model and on saas_portal create the specific _get_last_connection method. I can create in saas_base module 3 or 2 AbstractModels and in saas_portal and saas_server use the AbstractModels to create the local models. This allow to put in one place the common fields and also some behaviour.

I'm testing now on my code, it can do it quickly. Tell me if your consider something different about this design. I reached this point trying to call _create_new_database from create_template in saas_portal.plan as you request me. Also I'm still doing a review to many lines of code you created and I'm discovering now.

**Comment by yelizariev** [comment]
I think at this moment we can create saas_base.client and put there common fields.

Then 

    class SaasPortalClient(models.Model):
        _name = 'saas_portal.client'
        _description = 'Client'
        _rec_name = 'name'
    
        _inherit = ['mail.thread', 'saas_portal.database', 'saas_base.client']

    class SaasServerClient(models.Model):
        _name = 'saas_server.client'
        _inherit = ['mail.thread', 'saas_base.client']

I don't think that we need a separate model saas_server.database or any other refactoring. At least for now.

**Comment by yelizariev** [comment]
Finish  _create_new_database and saas_base.client refactoring , but in the future ask for refactoring only if you work on related part of code. Don't ask for refactoring if you only see something, that could be refactored. I think it's better to save some time and wait while we collect other updates, so we will not need make refactoring twice.
